language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm

script:
  - make test-all

after_script:
  - make coveralls