language: php

php:
  - 7.0

before_script:
  - nvm install 6
  - npm install
  - npm install --global bower
  - npm install --global gulp

matrix:
  fast_finish: true

script:
  - make test-all

after_script:
  - make coveralls