language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm

script:
  - npm install
  - bower install
  - gulp update
  - composer update-all
  - composer test

after_script:
  - composer coveralls